module.exports = {
	plugins: [
		{ cleanupAttrs: false },
		{ cleanupEnableBackground: false },
		{ cleanupIDs: false },
		{ cleanupListOfValues: false },
		{ cleanupNumericValues: false },
		{ collapseGroups: false },
		{ convertColors: false },
		{ convertPathData: false },
		{ convertShapeToPath: false },
		{ convertStyleToAttrs: false },
		{ convertTransform: false },
		{ mergePaths: false },
		{ moveElemsAttrsToGroup: false },
		{ moveGroupAttrsToElems: false },
		{ removeComments: false },
		{ removeDesc: false },
		{ removeDoctype: false },
		{ removeEmptyAttrs: false },
		{ removeEmptyContainers: false },
		{ removeEmptyText: false },
		{ removeHiddenElems: false },
		{ removeEditorsNSData: false },
		{ removeMetadata: false },
		{ removeNonInheritableGroupAttrs: false },
		{ removeRasterImages: false },
		{ removeTitle: false },
		{ removeUnknownsAndDefaults: false },
		{ removeUselessDefs: false },
		{ removeUnusedNS: false },
		{ removeUselessStrokeAndFill: false },
		{ removeXMLProcInst: false },
		{ sortAttrs: false },
	],
	floatPrecision: 2
};
